services:
  - type: web
    name: myvoterwisdom
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements-server.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
